### ISSUE TITLE
Functional errors of the running application

### ISSUE THREAD

**Issue by amarinso** [oasp/oasp4js#29]
Hi, I'm going through the client demo application running on "http://oasp-ci.cloudapp.net/" and I'm having some errors. Is it supposed to be fully working?

For example entering with cook it goes directly to cook-positions page, but if you click the Table menu there is no indication to go back to cook-positions (although browser back button goes back indeed)

Also entering with bartender I was hopping to enter to cook-positions with mealOrSideDish=false but instead goes directly to Table page.... so I can not get to cook-positions page.

Other thing that seems not right is that a table can be edited and have some orders without being "occupied"... I don't know if it makes sense

While trying the online demo I have some tables in occupied state that I'm unable to free because the server returns an IllegalEntityStateException, and also this error doesn't get to the UI so the user doesn't know whats happening.

I don't know if is the objective of the demo to have it fully working but it seems lacking.

By the way I'm being picky because I'm trying to replicate the client side demo with ExtJS5 so I've been playing lately with it to discover the functionality.

Thanks in advance

**Comment by hohwille** [comment]
@amarinso thanks for your feedback. You are entirely correct. I am aware of most of the problems and new see some new things. Thanks for your feedback. Some of the issues are very easy to fix and others will take some more time. Some issues are also about usability. There are also use-cases that are planned but not yet implemented. Also the reservation does not make sense and has to be redesigned entirely.
@mmatczak IMHO we should file little individual issues and bugs for the detailed aspects and get them fixed in the near future...

**Comment by MarcoRose** [comment]
resolved
