### ISSUE TITLE
Pagination example

### ISSUE THREAD

**Issue by lgoerlach** [oasp/oasp4js#35]
As described in https://github.com/oasp/oasp4j/issues/193, we should have an example for pagination in the client.
A basic implementation for the server has already been done, see https://github.com/oasp/oasp4j/pull/239. It includes general pagination support and REST services for the Order entity.

The client should include at least one reference implementation for each of the following cases:
* pagination of a search result list (e.g. tables, orders) with next/previous page buttons
* a search result list that loads further results when the user has scrolled to the bottom

I will start looking into this matter.

**Comment by lgoerlach** [comment]
Pagination for tables with next/previous page buttons seems to work fine in my fork.

For the second case, https://github.com/sroze/ngInfiniteScroll looks quite promising. But I'm not sure where to use that approach because I couldn't find an entity in the example where this kind of scrolling wouldn't look silly ;-)
Suggestions are very welcome.

When I've implemented both cases, I will provide a pull request.

**Comment by hohwille** [comment]
we once said that we are going to use ui-grid (http://ui-grid.info).
The issue was lost when the repos were merged and the old oasp4js repo now also has been deleted.

Infinite scroll example for ui-grid is here:
http://ui-grid.info/docs/#/tutorial/212_infinite_scroll

Reasonable use-case will be the admin view on orders (including closed orders) that does not yet exist. However the cook-view might also make use of that for open order positions if the restaurant will be big and crowded...

**Comment by MarcoRose** [comment]
solved
