### ISSUE TITLE
Guided Project TH Köln - 0.2: Show some dishes at the homepage or login page

### ISSUE THREAD

**Issue by aburghcap** [oasp/oasp4js#72]
Part of the Guided Project at Technische Hochschule Köln - #48  

Idea:
To get started with our student's OASP project we wanted to extend the restaurant application's homepage and/or login page with an impressive list of some selected dishes - similar to a real restaurant placing a sign at the street with its actual offerings.

After having planned this at the sprint planning last thursday the students send the attached UI designs.

Any comments on that?

Should we place the dishes at the homepage or login page?

![loginpagedishestextual](https://cloud.githubusercontent.com/assets/11456980/10670957/5bab39fe-78e8-11e5-84da-b6185638c088.png)
![loginpagedishespictures](https://cloud.githubusercontent.com/assets/11456980/10670958/5bb2a8c4-78e8-11e5-97b7-0e58fa580bda.png)
![loginpagedishespaging](https://cloud.githubusercontent.com/assets/11456980/10670959/5bb62bca-78e8-11e5-84e3-3ab43dcce39a.png)

**Comment by szendo** [comment]
It looks good, but we don't need it. It's the website for restaurant management, not for customers.

**Comment by szendo** [comment]
It looks good, but i think that only restaurant employees can see this website

**Comment by sobkowiak** [comment]
Perhaps a new page for customers, where soeone could make a table reservation in the restaurant? Such a dialog could display selected dishes (or even the complete menu). Probably a new use case will be necessary in the restaurant backend.

**Comment by szendo** [comment]
I think, new page for customers or menu management will be a nice part of app.
Probably menu management will be easier.

**Comment by dumbNickname** [comment]
Hey,

I would also see those recommended dishes elsewhere. I would rather think about a view that can be displayed on restaurant monitors to show the customers what are the dishes of the day or some recommended ones. Something like a nice carousel would be enough. 

When it comes to the design of proposals, personally I like the second one most. Nevertheless, I agree with szendo that those nice designs do not fit the business requirements. It should be clear who is supposed to use the app. Current state of the app suggests that it is designed for employees. There are still many things missing and some of the existing views are not so exciting, so I would consider to fulfill existing implementation needs instead of adding new business requirements.

Cheers,
Bartek

**Comment by dumbNickname** [comment]
I do not mind adding eye-catchy features (just the opposite - I would strongly (:D) recommend do so), however I would simply like to have those new features useful and aligned with application goal (and imho we really need to find some new ideas for existing views, where we unnecessarily overuse trNgGrid tables). 
I think that developing proposed components on a separate branch will not be a problem. I really hope that the students will take lots of fun out of this task! :) Later on, one of the admins/architects will decide how they feel about those changes. I am only sharing my personal feelings/opinions :P

Last, small remark: Please design and later implement all the views with interface responsiveness in your minds (what you probably do anyway) . I just wanted to remind that we have bootstrap included in the project, so it would be great to take advantage of its layouting and grid system features wherever possible (this is another thing that is not really visible in our current views). 

In this particular case it would be nice to show some view proposals for mobile devices as well.

Cheers,
Bartek

**Comment by aburghcap** [comment]
Hello,
agreed that new functionality should fit business requirements and existing functionality should be improved. 

Two points on that:
- The students need a bigger goal than to work on issues in our existing dialogs so that they can benefit for their study. Under this constraints we have negotiated to work on new functionality. Our main goal is to demonstrate the potential of OASP4JS.
 
- Are there any business requirements we can read? My past investigations had brought no result so far.

**Comment by dumbNickname** [comment]
Hi,

Unfortunately I am quite new to OASP project as well and I do not know the docs very well, moreover I would not be surprised if such business requirements were not defined at all or at least not written down. 

But if I can meddle, I would propose to address some of the administration related topics, e.g.
- tables management (adding/removing/setting capacity). Imho, we could also think about introducing data such as tables placement in the restaurant, what would later give some visualization possibilities (something like a small map for new/fresh employed waiters to check where the order should be delivered. It would be also useful for bigger restaurants, but there many rooms might be available, so again some thinking needs to be done about the user interface).
- menu management (adding/removing dishes/setting recommended meals)
- employee management 
- admin dashboard with some statistics etc.
- and whatever more an admin would like to do :P

You can also think about some other topics like:
- face recognition login
- food ordering for takeaway
- new redesigned view for the cooks that can be properly used with a screen reader and fully operated via speech recognition or gestures  (the cooks would not need to wash their hands just to switch the state of the order)
- collecting data about most popular dishes or other user preferences grouped by some factor like a day of a week in order to provide estimated shopping needs for next weeks or just for monitoring how user preferences change in order to adjust the menu. 
All of those are just rough ideas from the top of my head, but maybe somebody will extend those with some reasonable, more or less related proposals. If any new ideas come to my mind I will share those as well.

Disclaimer - I have no power to decide about OASP development direction, I am just sharing my opinions.

Cheers,
Bartek

**Comment by aburghcap** [comment]
After this discussion above and having talked with a leading community member we decided that the students of TH Köln will 
a) implement the **second UI design** showing three dishes with big photos,
b) **integrate** this list of dishes into the existing **login dialog** of the **devonfw Restaurant sample application**,
c) implement one (perhaps random) selection of the three dishes to be listed,
c) localize the title "Unsere Topseller".

Further development will form a new additional domain of the restaurant application called _Recipes_ - decoupled from the existing functionality.

**Comment by MarcoRose** [comment]
Most ideas presented here are very valid and need to be developed in a sustainable way. So far a community-approach for this is missing. 

So, yesterday I opened a new WIKI to colloboratively work on a comprehensive vision of the business background of the OASP restaurant example. You will find it in the new Repo: https://github.com/oasp/oasp-business-vision/wiki. Please contribute.

If possible, university activities should be directed to add to the big picture, though this is not imperative. Sometimes a little freedom motivates better.

**Comment by aburghcap** [comment]
gut!

**Comment by aburghcap** [comment]
STATUS UPDATE:
Mostly done.

The authentification necessary for getting the recipe data before a user has logged caused some trouble. The students have fixed this in their fork. Looks as attached when I reviewed it on the student's integration environment.

They are getting to finish this for a pull request into OASP4JS dev during the actuall sprint (to weeks to go)...
![recipeslistatloginpage_issue 72](https://cloud.githubusercontent.com/assets/11456980/11085937/583c585c-884c-11e5-9148-7cecbc12cb77.JPG)

**Comment by aburghcap** [comment]
closed - no further work planned on this
